### ISSUE TITLE
Tasmota mit Solarflow welche Einheit muss der Sensor haben 

### ISSUE THREAD

**Issue by horstvogel** [z-master42/solarflow#19]
Moin,
bei mir mit einem Tasmota Sensor der via template Sensor erzeugt wir, da funktioniert das nicht. 

muss der Wert in kW oder W sein? Und muss der negativ sein? Oder darf nur größer 0 Einspeisung als Betrag dargestellt werden? Oder ist schlichtweg die 5 Sekunden bei mir vielleicht etwas kurz
Danke! 

      - name: "Leistunginwatt"
        state: "{{ states('sensor.tasmota_sml_power_curr') | float / 1 }}"
        unique_id: "leistung_in_watt_gesamtmessung"
        unit_of_measurement: W
        state_class: measurement
        device_class: power

**Comment by horstvogel** [comment]
Bei mir war das Problem dann 5 Sekunden, auf 15 Sekunden verändert und dann passte das.

**Comment by z-master42** [comment]
Wo bist du da jetzt gerade? Wo ist der Zusammenhang zum SolarFlow?

PS: Du brauchst nicht extra einen neuen Sensor erstellen um den Tasmota-Entitäten eine Einheit zu verpassen. Geht in der configuration.yaml und dann dort:
```
homeassistant:
  customize:
    sensor.tasmota_sml_power_curr:
      unit_of_measurement: W
      state_class: measurement
      device_class: power
```
