### ISSUE TITLE
Skripte für Hoymiles

### ISSUE THREAD

**Issue by MorreMor** [z-master42/solarflow#2]
Hi,
hab beide Skripte ausprobiert.
Nulleinspeisung funktioniert tadellos. Da ich aber auch gerne das andere Skript nutzen möchte (mit Begrenzung 10 % etc.) habe ich das auch ausprobiert. Hier fällt mir auf, dass die Limitsetzung sehr langsam und träge von statten geht. Also ich hab z.B. nur 200 Watt Bedarf und von 600 dauert es ca. 5 Minuten bis er die erreicht weil er in minimalen Schritten runtergeht. Warum ist das so?? Das ist bei dem anderen Skript nicht der Fall. Danke dir vorab!

**Comment by z-master42** [comment]
Hmm, ist mir so noch gar nicht aufgefallen. Dürfte aber eigentlich auch nicht sein, da das Kernskript ja identisch ist. Ich habe es für mich auch mittlerweile weiter angepasst, nur nicht mehr hier hochgeladen. Im Grunde kann man sich ja um die Kernfunktion drumherumbauen, was man möchte. Ich gucke aber noch mal rein, woran es denn liegen könnte.

**Comment by MorreMor** [comment]
Das wäre super. Wie hast du es denn angepasst? Habe das System erst seit gestern kenn mich aber zumindest ein wenig mit Home Assistant etc. Aus sonst hätte ich nicht beides über mqtt eingebunden bekommen ^^Mit freundlichen Grüßen Andreas Morawetz Am 07.09.2023 um 20:29 schrieb z-master42 ***@***.***>:﻿
Hmm, ist mir so noch gar nicht aufgefallen. Dürfte aber eigentlich auch nicht sein, da das Kernskript ja identisch ist. Ich habe es für mich auch mittlerweile weiter angepasst, nur nicht mehr hier hochgeladen. Im Grunde kann man sich ja um die Kernfunktion drumherumbauen, was man möchte. Ich gucke aber noch mal rein, woran es denn liegen könnte.

**Comment by z-master42** [comment]
Also aktuell sieht es so aus:
```
alias: Anpassung Wechselrichter Leistung
sequence:
  - repeat:
      while: []
      sequence:
        - if:
            - condition: state
              entity_id: binary_sensor.hoymiles_hm_600_reachable
              state: "on"
              alias: Wechselrichter erreichbar
          alias: "-"
          then:
            - variables:
                altes_limit: >-
                  {{
                  states('number.hoymiles_hm_600_limit_nonpersistent_absolute')
                  | float(1) }}
                grid_sum: >-
                  {{ states('sensor.volkszaehler_stromzahler_aktuelle_leistung')
                  | float(1) }}
                maximum_wr: "{{ 600 | float(1) }}"
                minimum_wr: "{{ 50 | float(1) }}"
                minimum_pack: "{{ 10 | int(1) }}"
                maximum_pack: "{{ 100 | int (1) }}"
                lower_limit_wr: "{{ 120 | float(1) }}"
                lower_limit_wr_morning: "{{ 12 | float(1) }}"
                pack_level: "{{ states('sensor.solarflow_electric_level') | int(1) }}"
                solar_input: "{{ states('sensor.solarflow_solar_input_power') | float(1) }}"
              alias: Variablen definieren
            - if:
                - condition: template
                  value_template: "{{ pack_level == maximum_pack }}"
                  alias: Akkustand = 100 %
              then:
                - if:
                    - condition: template
                      value_template: "{{ solar_input > maximum_wr }}"
                      alias: Solarleistung > maximale Wechselrichterleistung
                  then:
                    - service: number.set_value
                      data:
                        value: "{{ maximum_wr }}"
                      target:
                        entity_id: number.hoymiles_hm_600_limit_nonpersistent_absolute
                      alias: Setze Limit auf 600 W
                  else:
                    - if:
                        - condition: template
                          value_template: "{{ altes_limit < solar_input }}"
                          alias: Limit <= Solarleistung
                      then:
                        - service: number.set_value
                          data:
                            value: "{{ solar_input }}"
                          target:
                            entity_id: >-
                              number.hoymiles_hm_600_limit_nonpersistent_absolute
                          alias: Setze Limit = Solarleistung
                      alias: "-"
                  alias: "-"
              alias: "-"
              else:
                - if:
                    - condition: template
                      value_template: "{{ pack_level >= minimum_pack}}"
                      alias: Akkustand >= 10 %
                  then:
                    - variables:
                        setpoint: "{{ (grid_sum + altes_limit - 5.0) | float(1) }}"
                      alias: Neues Limit = Aktueller Verbrauch + Altes Limit - 5
                    - if:
                        - condition: template
                          value_template: "{{ setpoint > maximum_wr }}"
                          alias: Neues Limit > 600 W
                      then:
                        - service: number.set_value
                          data:
                            value: "{{ maximum_wr }}"
                          target:
                            entity_id: >-
                              number.hoymiles_hm_600_limit_nonpersistent_absolute
                          alias: Setze Limit auf 600 W
                      else:
                        - if:
                            - condition: template
                              value_template: "{{ setpoint < minimum_wr }}"
                              alias: Neues Limit < 50
                          then:
                            - service: number.set_value
                              data:
                                value: "{{ minimum_wr }}"
                              target:
                                entity_id: >-
                                  number.hoymiles_hm_600_limit_nonpersistent_absolute
                              alias: Setze Limit auf 50 W
                          else:
                            - if:
                                - condition: template
                                  value_template: "{{ setpoint != altes_limit }}"
                                  alias: Neues Limit != Altes Limit
                              then:
                                - service: number.set_value
                                  data:
                                    value: "{{ setpoint | float(1) }}"
                                  target:
                                    entity_id: >-
                                      number.hoymiles_hm_600_limit_nonpersistent_absolute
                                  alias: Setzte neues Limit
                              alias: "-"
                          alias: "-"
                      alias: "-"
                  else:
                    - if:
                        - condition: time
                          after: "04:00:00"
                          before: "12:00:00"
                          alias: Nach 0400 und vor 1200
                      then:
                        - service: number.set_value
                          data:
                            value: "{{ lower_limit_wr_morning }}"
                          target:
                            entity_id: >-
                              number.hoymiles_hm_600_limit_nonpersistent_absolute
                          alias: Setzte Limit auf 12 W
                      else:
                        - variables:
                            setpoint: "{{ (grid_sum + altes_limit - 5.0) | float(1) }}"
                          alias: Neues Limit = Aktueller Verbrauch + Altes Limit - 5
                        - if:
                            - condition: template
                              value_template: "{{ setpoint > lower_limit_wr }}"
                              alias: Neues Limit > 120 W
                          then:
                            - service: number.set_value
                              data:
                                value: "{{ lower_limit_wr }}"
                              target:
                                entity_id: >-
                                  number.hoymiles_hm_600_limit_nonpersistent_absolute
                              alias: Setze Limit auf 120 W
                          else:
                            - if:
                                - condition: template
                                  value_template: "{{ setpoint < minimum_wr }}"
                                  alias: Neues Limit < 50
                              then:
                                - service: number.set_value
                                  data:
                                    value: "{{ minimum_wr }}"
                                  target:
                                    entity_id: >-
                                      number.hoymiles_hm_600_limit_nonpersistent_absolute
                                  alias: Setze Limit auf 50 W
                              else:
                                - if:
                                    - condition: template
                                      value_template: "{{ setpoint != altes_limit }}"
                                      alias: Neues Limit != Altes Limit
                                  then:
                                    - service: number.set_value
                                      data:
                                        value: "{{ setpoint | float(1) }}"
                                      target:
                                        entity_id: >-
                                          number.hoymiles_hm_600_limit_nonpersistent_absolute
                                      alias: Setzte neues Limit
                                  alias: "-"
                              alias: "-"
                          alias: "-"
                      alias: "-"
        - delay:
            hours: 0
            minutes: 0
            seconds: 9
            milliseconds: 0
          alias: Warte 9 s
    alias: Solange
mode: single
icon: phu:huawei-solar-inverter
```
Aber das ist sicher noch nicht das Ende. Man findet immer was 😂
