### ISSUE TITLE
Pack und Home Power

### ISSUE THREAD

**Issue by TheVanDoom** [z-master42/solarflow#24]
Hey,

vielen Dank für die super Anleitung. Sorry, wenn ich da jetzt so doof fragen muss, aber gibt es eine Möglichkeit einzusehen, wie die Sensoren genau benannt sind? Es geht um die Pack Input/Output und Home Power. Ich sehe im state, dass hin und wieder ein Wert dafür kommt, aber angezeigt wird leider nichts (es bleibt bei 0). Meine Vermutung war nun, da ja auch der Hinweis daneben steht, dass man es an den Entitätsnamen anpassen solle, dass die vielleicht anders heißen? Solar-Power 1 und 2 kommen an, also scheint da der Sensor zu passen.

**Comment by z-master42** [comment]
Wenn du in Home Assistant auf die Entitätseigenschaften gehst (über das Zahnrad), siehst du ja, wie der Sensor schlussendlich heißt.

Beispiel:
![Screenshot_20240529-113540.png](https://github.com/z-master42/solarflow/assets/66380371/619b0941-96dc-452d-8a63-253a158a987e)

**Comment by TheVanDoom** [comment]
Hmm, ok. Also für z.B. `sensor.solarflow_solar_input_power` habe ich definitiv einen Wert (wenn ich den check im template rausnehme, bekomme ich auch was im Dashboard angezeigt). Er scheint aber bei der Prüfung des sensors dennoch immer in den else-Fall zu gehen.

**Comment by z-master42** [comment]
Ah, ich denke ich habe den Fehler gefunden.

Ändere das `int('Sensorname', 0)` mal auf `states('Sensorname') | int(0)`

**Comment by z-master42** [comment]
Ich glaube ich habe den Fehler gefunden.

Mach mal aus `int(value_json..., 0)` `value_json... | int(0)`.

**Comment by TheVanDoom** [comment]
> Ich glaube ich habe den Fehler gefunden.
> 
> Mach mal aus `int(value_json..., 0)` `value_json... | int(0)`.
> 
> Scheinbar geht das hier mit einer Funktion nicht, sondern nur mit der Filtervariante.
> 
> Ist auch irgendwie klar: int() erwarten einen Integer und keinen Text... 🤦‍♂️

Das greift aber nur, wenn auch der sensor erkannt wird, er also in den else-Zweig läuft. Aktuell erkennt er nicht, dass der sensor nen Wert hat.

**Comment by z-master42** [comment]
Doch er setzt aber im if-Zweif den Default-Wert 0, da das Wort value_json... keine Zahl ist.

**Comment by TheVanDoom** [comment]
Nur kommt er nie in den If-Zweig. Ich hab zum testen jetzt einfach mal in beide Zweige nen fixen Wert geschrieben. Er geht immer auf den else-fall.

```
  - name: "Solar Input Power"
    unique_id: "<deviceID>solarInputPower"
    state_topic: "<key>/<deviceID>/state"
    unit_of_measurement: "W"
    device_class: "power"
    value_template: >
      {% if states('sensor.solarflow_solar_input_power') not in ['unknown'] %} # Muss ggf. an euren Entitätsnamen angepasst werden
        {{ int(1000) }}
      {% else %}
        {{ int(0) }}
      {% endif %}
    state_class: "measurement"
    device:
      name: "SolarFlow"
      identifiers: "<HubID>"
      manufacturer: "Zendure"
      model: "SmartPV Hub 2000 Controller"
```
