### ISSUE TITLE
Keine Werte für solarInputPower, solarPower1 und solarPower2

### ISSUE THREAD

**Issue by da666er** [z-master42/solarflow#34]
Erstmal vielen Dank für Deine Bemühungen hier!

Einbindung in HA lief grundsätzlich reibungslos (Bridged MQTT mit manueller Anlage).
Nur leider bekomme ich für diese Entitäten keine Werte:
- solarInputPower
- solarPower1
- solarPower2

Sieht in HA dann so aus:

![image](https://github.com/user-attachments/assets/b9020d6e-66d1-4577-9db9-23f450acf545)

Ne Idee an was das liegen kann?

Ich poste hier mal die entsprechenden Stellen aus meiner mqtt.yaml:

```
    - name: "Solar Input Power"
      unique_id: "<deviceID>solarInputPower"
      state_topic: "<appKey>/<deviceID>/state"
      unit_of_measurement: "W"
      device_class: "power"
      value_template: >
        {% if states('sensor.solarflow_solar_input_power') not in ['unknown'] %}
          {{ int(value_json.solarInputPower, 0) }}
        {% else %}
          {{ int(0) }}
        {% endif %}
      state_class: "measurement"
      device: 
        name: "SolarFlow"
        identifiers: "<PVHubSeriennummer>"
        manufacturer: "Zendure"
        model: "SmartPV Hub 2000 Controller"
    - name: "Solar Power 1"
      unique_id: "<deviceID>solarPower1"
      state_topic: "<appKey>/<deviceID>/state"
      value_template: >
        {% if states('sensor.solarflow_solar_power_1') not in ['unknown'] %}
          {{ int(value_json.solarPower1, 0) }}
        {% else %}
          {{ int(0) }}
        {% endif %}
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      device: 
        name: "SolarFlow"
        identifiers: "<PVHubSeriennummer>"
        manufacturer: "Zendure"
        model: "SmartPV Hub 2000 Controller"

    - name: "Solar Power 2"
      unique_id: "<deviceID>solarPower2"
      state_topic: "<appKey>/<deviceID>/state"
      value_template: >
        {% if states('sensor.solarflow_solar_power_2') not in ['unknown'] %}
          {{ int(value_json.solarPower2, 0) }}
        {% else %}
          {{ int(0) }}
        {% endif %}
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      device: 
        name: "SolarFlow"
        identifiers: "<PVHubSeriennummer>"
        manufacturer: "Zendure"
        model: "SmartPV Hub 2000 Controller"
```

Edit:
Via MQTT Explorer bekomme ich diese Werte ohne Probleme geliefert...

![image](https://github.com/user-attachments/assets/5c7267e6-062f-44ed-8986-85b84297397f)
