### ISSUE TITLE
Einbindung von mehreren Hubs

### ISSUE THREAD

**Issue by BieberleA** [z-master42/solarflow#52]
Hallo, kurze Frage: Kann ich - wie in der SolarFlowApp auch - mehrere Geräte via MQTT einbinden? Theoretisch sind die Einwahl- bzw. Kontodaten `"appkey"` und `"appSecret"` ja identisch und man müsste "nur" im `mqtt.yaml` File neue Sensoren mit einer anderen/neuen ID hinzufügen? 

Muss man bei der Definition der Sensoren noch mehr beachten, z.B.:

```
sensor:
     - name: "Hub State"
       unique_id: "<deviceID>hubState"
       state_topic: "<appKey>/<deviceID>/state"
       value_template: "{{ value_json.hubState | int }}"
       device: 
         name: "SolarFlow"
         identifiers: "<EurePVHubSeriennummer>"
         manufacturer: "Zendure"
         model: "SmartPV Hub 1200 Controller Nr 2"
```
die Eigenschaft `"name"` auch noch ändern (wegen eventueller doppelter Definition)? Oder reicht die Änderung der `"unique_id"` aus? Danke.
